config/routes.rb
Flixter::Application.routes.draw do
  get "replies/new"
  get "replies/create"
  devise_for :users

  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  resource :dashboards, only: [:show]
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
    resources :comments, only: [:create]
    resources :topics, only: [:new, :create]
  end
  resources :topics do
    resources :posts, only: [:new, :create]
  end
  resources :posts do
    resources :replies, only: [:new, :create]
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :sections
  has_many :enrollments
  has_many :comments
  has_many :topics
  before_create :build_topic

  validates :title, :description, :cost, presence: { message: 'This field cannot be blank!' }
  validates :cost, numericality: { greater_than_or_equal_to: 0, message: 'The value must be greater than zero!' }

  def free?
    cost.zero?
  end

  def premium?
    !free?
  end

  def latest_posts
    Post.latest_posts_for_course(self.id)
  end

  private

  def build_topic
    self.topics.build(:name => "General Questions")
  end
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, :with_same => :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end

  def previous_lesson
    lesson = section.lessons.where("row_order < ?", self.row_order).rank(:row_order).last
    if lesson.blank? && section.previous_section
      return section.previous_section.lessons.rank(:row_order).last
    end
    return lesson
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  belongs_to :original_post, :class_name => 'Post'
  has_many :replies, :class_name => 'Post', :foreign_key => 'original_post_id'
  scope :latest_posts_for_course, ->(course_id) { joins(topic: {course: :sections}).where('courses.id = ?', course_id).order(created_at: :desc).limit(3) }
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
  end

  def previous_section
    course.sections.where("row_order < ?", self.row_order).rank(:row_order).last
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :course
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :courses
  has_many :enrollments
  has_many :comments
  has_many :posts
  has_many :enrolled_courses, through: :enrollments, source: :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    enrolled_courses.include?(course)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @section = Section.new
    @comment = Comment.new
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]

  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render text: 'Updated!'
  end

  private

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrolled_in_current_course

  def show
    @course = Lesson.find(params[:id]).section.course
    @posts = @course.latest_posts
  end

  private

  def require_enrolled_in_current_course
    if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), alert: 'Please enroll in the course to watch the lessons.'
    end
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
end

# select p.* from courses c join sections s on s.course_id = c.id join lessons l on l.section_id = s.id
#   join topics t on t.course_id = c.id join posts p on p.topic_id = t.id group by p.id;

#   Category.joins(posts: [{comments: :guest}, :tags])

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def new
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @topic.posts.create(post_params.merge({:user_id => current_user.id}))
    redirect_to topic_path(@topic)
  end

  def show
    @post = Post.find(params[:id])
    @replies = @post.replies
    @reply = Post.new(:original_post_id => @post.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @reply = @post.replies.build
  end

  def create
    @post = Post.find(params[:post_id])
    @post.replies.create(post_params.merge({:user_id => current_user.id}))
    redirect_to post_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.find(params[:course_id])
    @topic = @course.topics.new
  end

  def create
    @course = Course.find(params[:course_id])
    @course.topics.create(topic_params)
    redirect_to topics_path
  end

  def show
    @topic = Topic.find(params[:id])
    @post = Post.new
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/lessons/show.html.erb
<br>
<div class="col-sm-9">
  <div class="booyah-box col-sm-12">
    <h1 class><%= current_lesson.title %></h1>
    <h4 class="pull-left lesson-subtitle"><%= current_lesson.subtitle %></h4>

    <% if current_lesson.next_lesson.present? %>
      <%= link_to lesson_path(current_lesson.next_lesson), :class => 'btn btn-default btn-lesson pull-right' do %>
        Next Lesson &nbsp;
        <span class="glyphicon glyphicon-forward"></span>
      <% end %>
    <% end %>

    <% if current_lesson.previous_lesson.present? %>
      <%= link_to lesson_path(current_lesson.previous_lesson), :class => 'btn btn-default btn-lesson pull-right' do %>
        <span class="glyphicon glyphicon-backward"></span>
        &nbsp; Previous Lesson
      <% end %>
    <% end %>

    <div class="clear"></div>

    <video id="MY_VIDEO_1" class="video-js vjs-default-skin vjs-big-play-centered" controls
    preload="auto" width="auto" height="auto" poster="/assets/black.jpg"
    data-setup="{}">
    <source src="<%= current_lesson.video.to_s %>" type='video/mp4'>
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
    </video>
  </div>
</div>
<div class="col-sm-3">
  <% @posts.each do |post| %>
    <div class="booyah-box col-sm-12 text-center">
      <h3><%= link_to post.title, post_path(post) %></h3>
    </div>
  <% end %>
  <div class="booyah-box col-sm-12 text-center">
    <h3>Do you have a question?</h3>
    <br>
    <!-- Button trigger modal -->
    <button class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
      Start a Discussion
    </button>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
      </div>
      <div class="modal-body">
        <%#= simple_form_for @comment, :url => course_comments_path(@course) do |f| %>
          <%#= f.input :message %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%#= f.submit "Add a Comment", :class => 'btn btn-primary' %>
      </div>
      <%# end %>
    </div>
  </div>
</div>