config/routes.rb
Flixter::Application.routes.draw do
  get "replies/new"
  get "replies/create"
  devise_for :users

  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  resource :dashboards, only: [:show]
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
    resources :comments, only: [:create]
    resources :topics, only: [:new, :create]
  end
  resources :topics do
    resources :posts, only: [:new, :create]
  end
  resources :posts do
    resources :replies, only: [:new, :create]
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :sections
  has_many :enrollments
  has_many :comments
  has_many :topics
  before_create :build_topic

  validates :title, :description, :cost, presence: { message: 'This field cannot be blank!' }
  validates :cost, numericality: { greater_than_or_equal_to: 0, message: 'The value must be greater than zero!' }

  def free?
    cost.zero?
  end

  def premium?
    !free?
  end

  def latest_posts
    Post.latest_posts_for_course(self.id)
  end

  private

  def build_topic
    self.topics.build(:name => "General Questions")
  end
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, :with_same => :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end

  def previous_lesson
    lesson = section.lessons.where("row_order < ?", self.row_order).rank(:row_order).last
    if lesson.blank? && section.previous_section
      return section.previous_section.lessons.rank(:row_order).last
    end
    return lesson
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  belongs_to :original_post, :class_name => 'Post'
  has_many :replies, :class_name => 'Post', :foreign_key => 'original_post_id'
  scope :latest_posts_for_course, ->(course_id) { joins(topic: {course: :sections}).where('courses.id = ?', course_id).order(created_at: :desc).limit(3) }
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
  end

  def previous_section
    course.sections.where("row_order < ?", self.row_order).rank(:row_order).last
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :course
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :courses
  has_many :enrollments
  has_many :comments
  has_many :posts
  has_many :enrolled_courses, through: :enrollments, source: :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    enrolled_courses.include?(course)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @section = Section.new
    @comment = Comment.new
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_enrolled_in_current_course

  def show
    @course = Lesson.find(params[:id]).section.course
    @posts = @course.latest_posts
  end

  private

  def require_enrolled_in_current_course
    if !current_user.enrolled_in?(current_lesson.section.course)
      redirect_to course_path(current_lesson.section.course), alert: 'Please enroll in the course to watch the lessons.'
    end
  end

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end
end

# select p.* from courses c join sections s on s.course_id = c.id join lessons l on l.section_id = s.id
#   join topics t on t.course_id = c.id join posts p on p.topic_id = t.id group by p.id;

#   Category.joins(posts: [{comments: :guest}, :tags])

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def new
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @topic.posts.create(post_params.merge({:user_id => current_user.id}))
    redirect_to topic_path(@topic)
  end

  def show
    @post = Post.find(params[:id])
    @replies = @post.replies
    @reply = Post.new(:original_post_id => @post.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @reply = @post.replies.build
  end

  def create
    @post = Post.find(params[:post_id])
    @post.replies.create(post_params.merge({:user_id => current_user.id}))
    redirect_to post_path(@post)
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.find(params[:course_id])
    @topic = @course.topics.new
  end

  def create
    @course = Course.find(params[:course_id])
    @course.topics.create(topic_params)
    redirect_to topics_path
  end

  def show
    @topic = Topic.find(params[:id])
    @post = Post.new
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/posts/new.html.erb
This is a test.

app/views/posts/show.html.erb
<div class="booyah-box col-sm-10 col-sm-offset-1">
  <h2><%= @post.title %></h2>
  <hr class="clear">
  <div class="col-sm-3 text-right">
    <p>
      Posted by: <%= @post.user.email %><br>
      <%= @post.created_at.strftime("%D") %>
    </p>
  </div>
  <div class="col-sm-9">
    <p><%= @post.body %></p>
  </div>
  <% @replies.each do |reply| %>
    <hr class="clear">
    <div class="col-sm-3 text-right">
      <p>
        Posted by: <%= reply.user.email %><br>
        <%= reply.created_at.strftime("%D") %>
      </p>
    </div>
    <div class="col-sm-9">
      <p><%= raw reply.body %></p>
    </div>
  <% end %>
  <div class="clear"></div>
  <% if current_user %>
    <hr class="clear">
    <%= simple_form_for @reply, :url => post_replies_path(@post) do |f| %>
      <%= f.input :body, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} }, :label => false, :placeholder => "Post a reply..." %>
      <%= f.submit "Reply", class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>

app/views/topics/index.html.erb
  <div class="booyah-box col-sm-10 col-sm-offset-1">
    <h1>Forum Topics</h1>

    <div class="col-sm-12">
      <% @courses.each do |course| %>
        <% unless course.topics.empty? %>
          <hr class="clear">
          <% if course.user == current_user %>
            <%= link_to "Add Topic", new_course_topic_path(course), class: "btn btn-primary btn-xs btn-lesson pull-right" %>
          <% end %>
          <h3><%= course.title %></h3>
          <ul>
            <% course.topics.each do |topic| %>
              <li class="clear">
                <% if course.user == current_user %>
                  <%= link_to "Delete Topic", topic_path(topic), method: :delete, class: "btn btn-danger btn-lesson btn-xs pull-right" %>
                <% end %>
                <h4><%= link_to topic.name, topic_path(topic) %></h4>
              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/topics/new.html.erb
<div class="booyah-box col-sm-6 col-sm-offset-3">
  <h1>Add A New Topic</h1>
  <%= simple_form_for @topic, :url => course_topics_path(@course) do |f| %>
    <%= f.input :name %>
    <br />
    <%= f.submit "Create Topic", :class => 'btn btn-primary' %>
    <br />
  <% end %>
</div>

app/views/topics/show.html.erb
<div class="booyah-box col-sm-10 col-sm-offset-1">
  <h1><%= @topic.name %></h1>
  <br>

  <div class="col-sm-8 col-sm-offset-1">
    <h3>Title</h3>
  </div>
  <div class="col-sm-2 text-center">
    <h3>Replies</h3>
  </div>
  <% @topic.posts.each do |post| %>
    <hr class="clear col-sm-10 col-sm-offset-1">
    <div class="col-sm-8 col-sm-offset-1">
      <h4><%= link_to post.title, post_path(post) %></h4>
    </div>
    <div class="col-sm-2 text-center">
      <%= post.replies.count %>
    </div>
  <% end %>
  <br class="clear">
  <br>
  <div class="col-sm-offset-1 col-sm-5">
    <%= link_to "Back", topics_path, class: "btn btn-default" %>
    <% if current_user %>
      <!-- Button trigger modal -->
      <button class="btn btn-success" data-toggle="modal" data-target="#myModal">
        Create Post
      </button>
    <% end %>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
        </div>
        <%= simple_form_for @post, :url => topic_posts_path(@topic) do |f| %>
          <div class="modal-body">
              <%= f.input :title %>
              <%= f.input :body %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Comment", :class => 'btn btn-primary btn-lesson' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>