config/routes.rb
Flixter::Application.routes.draw do
  get "replies/new"
  get "replies/create"
  devise_for :users

  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  resource :dashboards, only: [:show]
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
    resources :comments, only: [:create]
    resources :topics, only: [:new, :create]
  end
  resources :topics do
    resources :posts, only: [:new, :create]
  end
  resources :posts do
    resources :replies, only: [:new, :create]
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :sections
  has_many :enrollments
  has_many :comments
  has_many :topics
  before_create :build_topic

  validates :title, :description, :cost, presence: { message: 'This field cannot be blank!' }
  validates :cost, numericality: { greater_than_or_equal_to: 0, message: 'The value must be greater than zero!' }

  def free?
    cost.zero?
  end

  def premium?
    !free?
  end

  def latest_posts
    Post.latest_posts_for_course(self.id)
  end

  private

  def build_topic
    self.topics.build(:name => "General Questions")
  end
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, :with_same => :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end

  def previous_lesson
    lesson = section.lessons.where("row_order < ?", self.row_order).rank(:row_order).last
    if lesson.blank? && section.previous_section
      return section.previous_section.lessons.rank(:row_order).last
    end
    return lesson
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  belongs_to :original_post, :class_name => 'Post'
  has_many :replies, :class_name => 'Post', :foreign_key => 'original_post_id'
  scope :latest_posts_for_course, ->(course_id) { joins(topic: {course: :sections}).where('courses.id = ?', course_id).order(created_at: :desc).limit(3) }
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
  end

  def previous_section
    course.sections.where("row_order < ?", self.row_order).rank(:row_order).last
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :course
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :courses
  has_many :enrollments
  has_many :comments
  has_many :posts
  has_many :enrolled_courses, through: :enrollments, source: :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    enrolled_courses.include?(course)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def new
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @topic.posts.create(post_params.merge({:user_id => current_user.id}))
    redirect_to topic_path(@topic)
  end

  def show
    @post = Post.find(params[:id])
    @replies = @post.replies
    @reply = Post.new(:original_post_id => @post.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.find(params[:course_id])
    @topic = @course.topics.new
  end

  def create
    @course = Course.find(params[:course_id])
    @course.topics.create(topic_params)
    redirect_to topics_path
  end

  def show
    @topic = Topic.find(params[:id])
    @post = Post.new
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flixter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="http://vjs.zencdn.net/4.6/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.6/video.js"></script>
  <style>
    .video-js {padding-top: 56.25%}
    .vjs-fullscreen {padding-top: 0px}
  </style>
</head>
<body>
  <div id="wrap">

    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#flixter-top-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Flixter', root_path, :class => 'navbar-brand' %>
          <!-- <a class="navbar-brand" href="#">Flixter</a> -->
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="flixter-top-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'See All Courses', courses_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Forum", topics_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "My Dashboard", dashboards_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="clear"></div>

    <% if notice.present? %>
      <p class="col-sm-12 alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="col-sm-12 alert alert-danger"><%= alert %></p>
    <% end %>

  <%= yield %>
</div> <!-- end #wrap -->
<br class="clear">
<br>
<%= debug(params) if Rails.env.development? %>
  <div id="footer">
    <div class="container">
      <div class="col-sm-3">
        <strong>Teachers</strong>
        <br>
        <%= link_to 'Teach a Course', new_instructor_course_path %>
        <br>
        <%= link_to 'My Dashboard', dashboards_path %>
      </div>
      <div class="col-sm-3">
        <strong>About</strong>
        <br>
        <%= link_to 'Team', team_path %>
        <br>
        <%= link_to 'Careers', careers_path %>
        <br>
        <%= link_to 'Privacy Policy', privacy_path %>
      </div>
      <div class="col-sm-3">
        <strong>Contact</strong>
        <br>
        info@flixter.com
        <br>
        Somewhere Downtown
        <br>
        Seattle, WA
      </div>
      <div class="col-sm-3 social">
        <strong>Social</strong><br>
        <%= link_to 'https://github.com' do %>
          <i class="fa fa-github fa-2x social-button"></i>
        <% end %>
        <%= link_to 'https://www.facebook.com' do %>
          <i class="fa fa-facebook-square fa-2x social-button"></i>
        <% end %>
        <%= link_to 'https://www.twitter.com' do %>
          <i class="fa fa-twitter fa-2x social-button"></i>
        <% end %>
      </div>
    </div>
  </div>

</body>
</html>